<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27502" started-at="2022-10-09T12:29:51 CDT" finished-at="2022-10-09T12:30:18 CDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27502" started-at="2022-10-09T12:29:51 CDT" finished-at="2022-10-09T12:30:18 CDT">
      <class name="testcases.TC_001">
        <test-method status="PASS" signature="loadPropertyFile()[pri:0, instance:testcases.TC_001@727803de]" name="loadPropertyFile" is-config="true" duration-ms="230" started-at="2022-10-09T12:29:51 CDT" finished-at="2022-10-09T12:29:51 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadPropertyFile -->
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:testcases.TC_001@727803de]" name="launchDriver" is-config="true" duration-ms="3238" started-at="2022-10-09T12:29:51 CDT" finished-at="2022-10-09T12:29:54 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="PASS" signature="logintest(java.lang.String)[pri:0, instance:testcases.TC_001@727803de]" name="logintest" duration-ms="12316" started-at="2022-10-09T12:29:54 CDT" data-provider="jsondata" finished-at="2022-10-09T12:30:07 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[tomsmith,SuperSecretPassword!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testcases.TC_001@727803de]" name="teardown" is-config="true" duration-ms="1402" started-at="2022-10-09T12:30:07 CDT" finished-at="2022-10-09T12:30:08 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:testcases.TC_001@727803de]" name="launchDriver" is-config="true" duration-ms="1891" started-at="2022-10-09T12:30:08 CDT" finished-at="2022-10-09T12:30:10 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="FAIL" signature="logintest(java.lang.String)[pri:0, instance:testcases.TC_001@727803de]" name="logintest" duration-ms="2182" started-at="2022-10-09T12:30:10 CDT" data-provider="jsondata" finished-at="2022-10-09T12:30:12 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[tomsmith,SuperSecretPasswor]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.TC_001.logintest(TC_001.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testcases.TC_001@727803de]" name="teardown" is-config="true" duration-ms="1137" started-at="2022-10-09T12:30:12 CDT" finished-at="2022-10-09T12:30:13 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:testcases.TC_001@727803de]" name="launchDriver" is-config="true" duration-ms="1963" started-at="2022-10-09T12:30:13 CDT" finished-at="2022-10-09T12:30:15 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="FAIL" signature="logintest(java.lang.String)[pri:0, instance:testcases.TC_001@727803de]" name="logintest" duration-ms="2199" started-at="2022-10-09T12:30:15 CDT" data-provider="jsondata" finished-at="2022-10-09T12:30:17 CDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[tom,SuperSecretPassword!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://the-internet.herokuapp.com/secure] but found [https://the-internet.herokuapp.com/login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testcases.TC_001.logintest(TC_001.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testcases.TC_001@727803de]" name="teardown" is-config="true" duration-ms="1140" started-at="2022-10-09T12:30:17 CDT" finished-at="2022-10-09T12:30:18 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.TC_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
